Algoritmo "algorithm exercises-Anna-04"

Var
emprestimo, total, valor_parcela:Real
parcelas: Inteiro


Inicio
      Escreva("Qual o valor do emprestimo? US$")
      Leia(emprestimo)
      Escreval("Informe a quantidade de parcelas: ")
      Leia(Parcelas)
      total <- emprestimo * 1.20
      valor_parcela <- total / parcelas
      Escreval("Total com juros: ", Total)
      Escreval("Quantidade de parcelas:", parcelas)
      Escreval(" Valor de cada parcela: R$", valor_parcela)
      





Fimalgoritmo